module.exports = {
    content: [
        './configurator/**/*.html',
        './configurator/js/**/*.js',
    ],
    safelist: [
        'bg-red-500',
        'text-3xl',
        'lg:text-4xl',
        'animate-wiggle',
        'animate-wiggle-more',
        'animate-rotate-y',
        'animate-rotate-x',
        'animate-jump',
        'animate-jump-in',
        'animate-jump-out',
        'animate-spin',
        'animate-ping',
        'animate-pulse',
        'animate-bounce',
        'animate-shake',
        'animate-fade',
        'animate-fade-down',
        'animate-fade-up',
        'animate-fade-left',
        'animate-fade-right',
        'animate-flip-up',
        'animate-flip-down',
        'animate-shake',
        'animate-fade',
        
        'animate-once',
        'animate-twice',
        'animate-thrice',
        'animate-infinite',
        'animate-normal',
        'animate-reverse',
        'animate-alternate',
        'animate-alternate-reverse',
        'animate-fill-forwards',
        'animate-fill-backwards',
        'animate-fill-both',
        'animate-delay-75',
        'animate-delay-100',
        'animate-delay-150',
        'animate-delay-200',
        'animate-delay-300',
        'animate-delay-500',
        'animate-delay-700',
        'animate-delay-1000',
        'animate-duration-75',
        'animate-duration-100',
        'animate-duration-150',
        'animate-duration-200',
        'animate-duration-300',
        'animate-duration-500',
        'animate-duration-700',
        'animate-duration-1000',
        'animate-duration-1500',
        'animate-duration-2000',
        'animate-duration-3000',
        'animate-duration-5000',

        'animate-ease-linear',
        'animate-ease-in',
        'animate-ease-out',
        'animate-ease-in-out',
        
    ],
    theme: {
        extend: {
            colors: {
                primary: '#AF5AC4',
                secondary: '#74EEFF',
                blue: {
                    DEFAULT: '#898CDA',
                    500: '#898CDA',
                },
                cyan: {
                    DEFAULT: '#74EEFF',
                    500: '#74EEFF',
                },
                violet: {
                    DEFAULT: '#AF5AC4',
                    50: '#FFF4FF',
                    100: '#FBEAFF',
                    200: '#F7D6FF',
                    300: '#E9AAF8',
                    500: '#AF5AC4',
                    700: '#5C2A74',
                    900: '#2F014B',
                },
                gray: {
                    DEFAULT: '#F1F2F7',
                    50: '#FBFBFE',
                    100: '#F1F2F7',
                    200: '#D7D7E2',
                    300: '#B1B2C1',
                    500: '#86879C',
                    700: '#52536D',
                    900: '#1B1C3B',
                },
            },
            fontFamily: {
                sans: ['Ubuntu', 'ui-sans-serif', 'system-ui', '-apple-system', 'Roboto', 'Arial', 'sans-serif'],
                mono: ['Ubuntu-Mono', 'ui-sans-serif', 'system-ui', '-apple-system', 'Roboto', 'Arial', 'sans-serif'],
            },
        },
    },
    plugins: [
        require('tailwindcss/plugin')(
            ({ addBase }) => addBase({
                '[x-cloak]': { display: 'none !important' },
            }),
        ),
        require('./src/index.js'),
    ],
}
